# Generated by Django 6.0.7 on 2026-07-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_created_at_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('STATE_ADMIN', 'State Admin'), ('DISTRICT_ADMIN', 'District Admin'), ('DOCTOR', 'Doctor'), ('LAB_TECHNICIAN', 'Lab Technician'), ('ASHA_WORKER', 'ASHA Worker'), ('DATA_ENTRY_OPERATOR', 'Data Entry Operator')], default='DATA_ENTRY_OPERATOR', max_length=30),
        ),
    ]
